male(alexander).
male(philip).
male(aristotle).
male(peter).
male(menelaus).
male(agamemnon).
male(achilles).
male(hector).
male(odysseus).

female(olympias).
female(helen).
female(clytemnestra).
female(hera).
female(andromache).
female(penelope).

parent(philip,alexander).
parent(olympias,alexander).
parent(alexander,hercules).
parent(peter,helen).
parent(helen,menelaus).
parent(olympias,helen).
parent(menelaus,hera).
parent(agamemnon,hector).
parent(clytemnestra,hector).
parent(agamemnon,achilles).
parent(clytemnestra,achilles).
parent(odysseus,telemachus).
parent(penelope,telemachus).

spouse(philip,olympias).
spouse(olympias,philip).
spouse(peter,helen).
spouse(helen,peter).
spouse(menelaus,helen).
spouse(helen,menelaus).
spouse(agamemnon,clytemnestra).
spouse(clytemnestra,agamemnon).
spouse(achilles,andromache).
spouse(andromache,achilles).
spouse(odysseus,penelope).
spouse(penelope,odysseus).

father(X,Y):-parent(X,Y),male(X).
mother(X,Y):-parent(X,Y),female(X).
grandfather(X,Y):-father(X,O),parent(O,Y).
grandmother(X,Y):-mother(X,O),parent(O,Y).
husband(X,Y):-spouse(X,Y),male(X).
wife(X,Y):-spouse(X,Y),female(X).
brother(X,Y):-parent(O,X),parent(O,Y),male(X),X\=Y.
sister(X,Y):-parent(O,X),parent(O,Y),female(X),X\=Y.
